require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    
RSpec/MessageSpies:
  EnforcedStyle: receive
    
RSpec/MultipleMemoizedHelpers:
  Max: 10
  
RSpec/MultipleExpectations:
  Max: 12
  
RSpec/ExampleLength:
  Max: 12

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
  
Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
