require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    
RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MessageSpies:
  EnforcedStyle: receive

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
